-- Migration: Add summary column to daily_lessons
-- Created: 2026-02-16

ALTER TABLE daily_lessons
ADD COLUMN IF NOT EXISTS summary TEXT;

-- Comment on column
COMMENT ON COLUMN daily_lessons.summary IS 'Short summary or lesson learned for the day (generated by AI)';
